services:
  - type: web
    name: AI-Powered-Smart-Disease-Prediction-System
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
